#!/usr/bin/env python3
"""
ND Legislature enriched RSS feed generator.
 
Reads the real ND Legislative Branch events feed (https://ndlegis.gov/events/feed),
which only ever gives a date for each notice, and produces a NEW feed
(docs/feed.xml) where each item's <description> also includes the specific
meeting time and room -- scraped from that notice's own page, the same way
nd_legis_sync.py does it.
 
This script never touches a calendar or Microsoft Graph. Its only job is
producing the enriched feed file. A separate consumer (e.g. a Power Automate
flow's Standard/free RSS connector) reads docs/feed.xml instead of the real
ndlegis.gov feed, and gets the time/room without needing a Premium HTTP
connector or any Microsoft admin consent -- the page-scraping work happens
here instead, outside of Power Automate entirely.
 
Intended to run on a schedule via GitHub Actions, with docs/feed.xml served
publicly via GitHub Pages. See GITHUB_SETUP.md for that part.
 
--- How caching works ---
 
Scraping every notice's page every single day would be wasteful (most
notices don't change day to day) and unnecessarily hammers ndlegis.gov with
requests. Instead, a small cache file (data/scraped_cache.json) remembers
what's already been scraped for a given notice (by its guid) and reuses that
on future runs. Only genuinely new notices trigger a real page fetch. A
notice whose meeting date has already passed is skipped entirely (never
scraped, never cached) since there's no reason to fetch a page for a meeting
that's already over.
 
This intentionally does NOT re-check/refresh already-cached notices (kept
simple, per request) -- if ndlegis.gov ever changes an already-cached
notice's time/room after the fact (e.g. a postponement), this script won't
notice. That's an accepted tradeoff for simplicity; the cache file can always
be deleted by hand to force a full re-scrape if that's ever suspected.
 
Cache entries for meetings more than CACHE_PRUNE_AFTER_DAYS days in the past
are automatically dropped on each run, so the cache file doesn't grow
forever with entries for meetings long since over.
 
--- How the exact meeting time is found ---
 
Each notice page has a "Download event to calendar" link, which turns out to
be an embedded iCalendar (.ics) data block right in the page's HTML (a
data:text/calendar;...;base64,... link, generated by a standard open-source
library called Spatie calendar-links) -- not a separate file you'd need to
fetch. It gives an exact, unambiguous UTC start/end time, which is far more
reliable than matching the page's visible wording (e.g. "10:00 AM to 2:15 PM
CDT"), since it's a fixed machine-readable format rather than natural-language
text that could subtly change. This script decodes that block first and only
falls back to the old text-matching approach if a page doesn't have one.
 
That embedded data does NOT include the room/building/location, though --
only title, start, end, and a link back to the notice -- so the location is
still found the same way as before: reading the page's visible "Location"
heading and the few short lines under it.
"""
 
from __future__ import annotations
 
import base64
import json
import re
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path
from xml.etree import ElementTree as ET
from xml.sax.saxutils import escape as xml_escape
from zoneinfo import ZoneInfo
 
import requests
from bs4 import BeautifulSoup
 
# North Dakota is in the Central time zone; ZoneInfo handles the CDT/CST
# daylight-saving switch automatically based on the actual date involved.
CENTRAL_TZ = ZoneInfo("America/Chicago")
 
# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
 
SOURCE_FEED_URL = "https://ndlegis.gov/events/feed"
 
# Where the enriched feed is written. docs/ is the conventional folder GitHub
# Pages serves from when a repo is configured for "Deploy from a branch" ->
# "/docs" -- see GITHUB_SETUP.md.
OUTPUT_DIR = Path(__file__).parent / "docs"
OUTPUT_FEED_FILE = OUTPUT_DIR / "feed.xml"
 
# Kept outside docs/ so it isn't publicly served -- not that it contains
# anything sensitive (it's all public meeting info), just no reason to.
CACHE_DIR = Path(__file__).parent / "data"
CACHE_FILE = CACHE_DIR / "scraped_cache.json"
 
# Cache entries for meetings older than this are dropped automatically each
# run -- see prune_cache() below. 30 days is comfortably past the point
# where a meeting's cached info could still matter to anything downstream.
CACHE_PRUNE_AFTER_DAYS = 30
 
# Identifies this script honestly in ndlegis.gov's server logs, and adds a
# small pause between page fetches -- basic good etiquette for a script that
# hits the same site repeatedly, even though this site doesn't publish a
# formal rate limit.
REQUEST_HEADERS = {"User-Agent": "nd-legis-feed-enricher/1.0 (personal automation; see GitHub repo)"}
DELAY_BETWEEN_FETCHES_SECONDS = 0.75
 
# Field separator used inside each enriched item's <description>. Chosen to
# be extremely unlikely to collide with real text, and easy to split() on
# from Power Automate. The resulting description looks like:
#   DATE|||2026-09-29|||START|||2026-09-29T10:00:00|||END|||2026-09-29T14:15:00|||
#   TZ|||CDT|||LOCATION|||Roughrider Room, State Capitol, Bismarck, ND|||DESC|||<text>
# so split(Feed Summary, '|||') gives a fixed-position array: index 1 = date,
# 3 = start time, 5 = end time, 7 = timezone, 9 = location, 11 = original
# description text. START/END are full local (Central time) ISO datetime
# strings ready to use directly as an event's Start time/End time -- no
# further date+time combining needed downstream. Both are the literal text
# "ALLDAY" when no time could be found at all for that notice (neither the
# embedded calendar data nor the page's visible text had one).
FIELD_SEP = "|||"
 
# Embedded iCalendar data URI on the notice page -- see the module docstring
# for what this is and why it's preferred over text-matching.
ICS_DATA_URI_RE = re.compile(r"data:text/calendar;charset=utf8;base64,([A-Za-z0-9+/=]+)")
ICS_DTSTART_RE = re.compile(r"DTSTART:(\d{8}T\d{6}Z)")
ICS_DTEND_RE = re.compile(r"DTEND:(\d{8}T\d{6}Z)")
 
# Fallback text patterns (same as nd_legis_sync.py) -- only used if a page
# doesn't have the embedded calendar data above. See that script's comments
# for why these match the page's visible text rather than specific HTML tags.
DATETIME_RANGE_RE = re.compile(
    r"([A-Za-z]+day,\s+[A-Za-z]+\s+\d{1,2},\s+\d{4})\s*-\s*"
    r"(\d{1,2}:\d{2}\s*[AP]M)\s*to\s*(\d{1,2}:\d{2}\s*[AP]M)\s*([A-Z]{2,4})?"
)
DATETIME_SINGLE_RE = re.compile(
    r"([A-Za-z]+day,\s+[A-Za-z]+\s+\d{1,2},\s+\d{4})\s*-\s*"
    r"(\d{1,2}:\d{2}\s*[AP]M)\s*([A-Z]{2,4})?"
)
URL_DATE_RE = re.compile(r"/events/(\d{4})/(\d{2})/(\d{2})/")
 
 
# ---------------------------------------------------------------------------
# Source feed parsing (same approach as nd_legis_sync.py)
# ---------------------------------------------------------------------------
 
def fetch_feed_items(feed_url: str) -> list[dict]:
    resp = requests.get(feed_url, headers=REQUEST_HEADERS, timeout=30)
    resp.raise_for_status()
    root = ET.fromstring(resp.content)
 
    items = []
    for item_el in root.findall("./channel/item"):
        def text(tag):
            el = item_el.find(tag)
            return el.text.strip() if el is not None and el.text else ""
 
        guid_el = item_el.find("guid")
        guid = guid_el.text.strip() if guid_el is not None and guid_el.text else None
 
        items.append(
            {
                "title": text("title"),
                "link": text("link"),
                "description": text("description"),
                "pubDate": text("pubDate"),
                "guid": guid,
            }
        )
    return items
 
 
def url_date(link: str) -> tuple[int, int, int] | None:
    """Pull (year, month, day) straight out of the notice URL -- see
    nd_legis_sync.py's url_date() for why this is trusted over the feed's
    description text."""
    m = URL_DATE_RE.search(link)
    if not m:
        return None
    year, month, day = (int(g) for g in m.groups())
    return year, month, day
 
 
def clean_description(raw: str) -> str:
    text = raw.replace("<br>", "\n").replace("&lt;br&gt;", "\n")
    text = re.sub(r"\s*\n\s*", " ", text).strip()
    # Strip the field separator if it somehow appears in real text, so it
    # can never be mistaken for a field boundary downstream.
    return text.replace(FIELD_SEP, "-")
 
 
# ---------------------------------------------------------------------------
# Per-notice page scraping (same approach as nd_legis_sync.py, plus the
# embedded-iCalendar-data improvement described in the module docstring)
# ---------------------------------------------------------------------------
 
def _parse_ics_utc_timestamp(raw: str) -> datetime:
    """Parse an iCalendar UTC timestamp like '20260929T150000Z'."""
    return datetime.strptime(raw, "%Y%m%dT%H%M%SZ").replace(tzinfo=ZoneInfo("UTC"))
 
 
def extract_ics_start_end(page_html: str) -> tuple[datetime, datetime | None] | None:
    """Look for the page's embedded 'Download event to calendar' iCalendar
    data and pull out precise UTC start/end times, if present. Returns
    (start_utc, end_utc_or_None), or None if this page doesn't have one or
    it couldn't be parsed -- callers should fall back to text-matching."""
    m = ICS_DATA_URI_RE.search(page_html)
    if not m:
        return None
    try:
        decoded = base64.b64decode(m.group(1)).decode("utf-8", errors="replace")
    except Exception:
        return None
 
    start_m = ICS_DTSTART_RE.search(decoded)
    if not start_m:
        return None
    try:
        start_utc = _parse_ics_utc_timestamp(start_m.group(1))
    except ValueError:
        return None
 
    end_utc = None
    end_m = ICS_DTEND_RE.search(decoded)
    if end_m:
        try:
            end_utc = _parse_ics_utc_timestamp(end_m.group(1))
        except ValueError:
            pass
 
    return start_utc, end_utc
 
 
def _combine_local_iso(ymd: tuple[int, int, int], time_12h: str) -> str | None:
    """Combine a (year, month, day) with page text like '10:00 AM' into a
    local ISO datetime string '2026-09-29T10:00:00'. Used only by the
    text-matching fallback path -- the embedded-calendar path already gives
    full timestamps directly."""
    year, month, day = ymd
    try:
        dt = datetime.strptime(f"{year}-{month:02d}-{day:02d} {time_12h}", "%Y-%m-%d %I:%M %p")
    except ValueError:
        return None
    return dt.strftime("%Y-%m-%dT%H:%M:%S")
 
 
def fetch_meeting_details(link: str) -> dict:
    """Best-effort scrape of the notice's own page for exact time + location.
 
    Returns a dict with start_iso/end_iso (local Central-time ISO datetime
    strings, e.g. '2026-09-29T10:00:00'), tz_abbr, and location -- any of
    which may be None if not found or if the page couldn't be fetched.
 
    Time is found in order of preference: (1) the page's embedded
    iCalendar data (precise, structured -- see module docstring), (2) the
    page's visible date/time wording, matched by pattern (best-effort, since
    this is natural-language text rather than a fixed format).
    """
    details = {"start_iso": None, "end_iso": None, "tz_abbr": None, "location": None}
    try:
        resp = requests.get(link, headers=REQUEST_HEADERS, timeout=30)
        resp.raise_for_status()
    except requests.RequestException as e:
        print(f"  (couldn't fetch page, will retry next run: {e})")
        return details
 
    # --- Preferred: embedded iCalendar data ---
    ics_result = extract_ics_start_end(resp.text)
    if ics_result:
        start_utc, end_utc = ics_result
        start_local = start_utc.astimezone(CENTRAL_TZ)
        details["start_iso"] = start_local.strftime("%Y-%m-%dT%H:%M:%S")
        details["tz_abbr"] = start_local.tzname()  # "CDT" or "CST", correct for the date
        if end_utc:
            details["end_iso"] = end_utc.astimezone(CENTRAL_TZ).strftime("%Y-%m-%dT%H:%M:%S")
 
    soup = BeautifulSoup(resp.text, "html.parser")
    text = soup.get_text("\n")
    lines = [ln.strip() for ln in text.splitlines()]
    lines = [ln for ln in lines if ln]
    full_text = "\n".join(lines)
 
    # --- Fallback: visible-text matching, only if the embedded data wasn't
    # present or couldn't be parsed ---
    if details["start_iso"] is None:
        ymd = url_date(link)
        start_12h = end_12h = tz_abbr = None
 
        m = DATETIME_RANGE_RE.search(full_text)
        if m:
            _, start_12h, end_12h, tz_abbr = m.groups()
        else:
            m = DATETIME_SINGLE_RE.search(full_text)
            if m:
                _, start_12h, tz_abbr = m.groups()
 
        if start_12h and ymd:
            start_iso = _combine_local_iso(ymd, start_12h)
            if start_iso:
                details["start_iso"] = start_iso
                details["tz_abbr"] = tz_abbr
                if end_12h:
                    end_iso = _combine_local_iso(ymd, end_12h)
                    if end_iso and end_iso <= start_iso:
                        # Crosses midnight (rare but possible).
                        end_dt = datetime.strptime(end_iso, "%Y-%m-%dT%H:%M:%S") + timedelta(days=1)
                        end_iso = end_dt.strftime("%Y-%m-%dT%H:%M:%S")
                    details["end_iso"] = end_iso
 
    # Location: the page has a literal "Location" heading (confirmed against
    # a real notice page during this build) followed by a few short lines --
    # room name, building, "City, ST", "United States". Anchor on that
    # heading itself rather than on "whatever follows the date/time line" --
    # the date/time is often immediately followed by other page furniture
    # (e.g. a "Download event to calendar" link) before "Location" actually
    # appears, which would otherwise get swept into the result.
    for i, line in enumerate(lines):
        if line.strip().lower() == "location":
            candidate_lines = []
            for nxt in lines[i + 1 : i + 6]:
                if len(nxt) > 60 or nxt.lower().startswith(("update", "meeting date")):
                    break
                candidate_lines.append(nxt)
                if nxt.strip().lower() == "united states":
                    break
            if candidate_lines:
                details["location"] = ", ".join(candidate_lines)
            break
 
    return details
 
 
# ---------------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------------
 
def load_cache() -> dict:
    if CACHE_FILE.exists():
        return json.loads(CACHE_FILE.read_text())
    return {}
 
 
def save_cache(cache: dict) -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    CACHE_FILE.write_text(json.dumps(cache, indent=2, sort_keys=True))
 
 
def prune_cache(cache: dict, today) -> int:
    """Remove cache entries for meetings whose date is more than
    CACHE_PRUNE_AFTER_DAYS days in the past, so the cache file doesn't grow
    forever with entries nothing will ever look up again.
 
    Entries written before the 'meeting_date' field existed (or where it's
    otherwise missing/unparseable) are left alone rather than guessed at or
    force-removed -- safer to keep a few extra harmless entries than to
    accidentally drop something we can't confirm is genuinely stale.
 
    Returns the number of entries removed."""
    cutoff = today - timedelta(days=CACHE_PRUNE_AFTER_DAYS)
    to_remove = []
    for guid, entry in cache.items():
        meeting_date_str = entry.get("meeting_date") if isinstance(entry, dict) else None
        if not meeting_date_str:
            continue
        try:
            meeting_date = datetime.strptime(meeting_date_str, "%Y-%m-%d").date()
        except ValueError:
            continue
        if meeting_date < cutoff:
            to_remove.append(guid)
 
    for guid in to_remove:
        del cache[guid]
    return len(to_remove)
 
 
# ---------------------------------------------------------------------------
# Enriched feed generation
# ---------------------------------------------------------------------------
 
def build_description_field(item: dict, details: dict) -> str:
    ymd = url_date(item["link"])
    date_str = f"{ymd[0]:04d}-{ymd[1]:02d}-{ymd[2]:02d}" if ymd else ""
 
    start = details.get("start_iso") or "ALLDAY"
    end = details.get("end_iso") or "ALLDAY"
    tz = details.get("tz_abbr") or ""
    location = details.get("location") or "(not posted)"
    original_desc = clean_description(item.get("description", "")) or "(no summary provided)"
 
    fields = [
        "DATE", date_str,
        "START", start,
        "END", end,
        "TZ", tz,
        "LOCATION", location,
        "DESC", original_desc,
    ]
    return FIELD_SEP.join(fields)
 
 
def write_feed_xml(enriched_items: list[dict]) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
 
    now = datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT")
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<rss version="2.0">',
        "<channel>",
        "<title>ND Legislature Events (enriched)</title>",
        "<link>https://ndlegis.gov/events/feed</link>",
        "<description>Auto-generated from the ND Legislative Branch events feed, "
        "with meeting time and location scraped from each notice's page.</description>",
        f"<lastBuildDate>{now}</lastBuildDate>",
    ]
    for it in enriched_items:
        parts.append("<item>")
        parts.append(f"<title>{xml_escape(it['title'])}</title>")
        parts.append(f"<link>{xml_escape(it['link'])}</link>")
        parts.append(f"<guid>{xml_escape(it['guid'])}</guid>")
        parts.append(f"<description>{xml_escape(it['enriched_description'])}</description>")
        if it.get("pubDate"):
            parts.append(f"<pubDate>{xml_escape(it['pubDate'])}</pubDate>")
        parts.append("</item>")
    parts.append("</channel>")
    parts.append("</rss>")
 
    OUTPUT_FEED_FILE.write_text("\n".join(parts), encoding="utf-8")
 
 
def validate_feed_xml() -> None:
    """Parse the just-written feed.xml back to confirm it's genuinely
    well-formed before the run is considered successful. Without this, a
    future code change that produced slightly broken XML would get written
    and published anyway, and Power Automate's RSS connector would just
    silently fail to read it the next day -- hard to notice, harder to
    diagnose. This makes that failure loud instead: a non-zero exit here
    fails the GitHub Actions run, which GitHub emails you about by default,
    the same day it happens."""
    try:
        ET.parse(OUTPUT_FEED_FILE)
    except ET.ParseError as e:
        raise SystemExit(f"Generated feed.xml is not valid XML -- not publishing it: {e}")
 
 
# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
 
def main() -> None:
    print(f"Fetching source feed: {SOURCE_FEED_URL}")
    items = fetch_feed_items(SOURCE_FEED_URL)
    print(f"Found {len(items)} item(s) in source feed.")
 
    cache = load_cache()
    today = datetime.utcnow().date()
 
    enriched_items = []
    scraped_count = 0
    cached_count = 0
    skipped_past_count = 0
    skipped_duplicate_count = 0
    seen_guids_this_run = set()
 
    for item in items:
        if not item["guid"]:
            continue
 
        if item["guid"] in seen_guids_this_run:
            # The source feed has been observed to list the same guid twice
            # with two different dates (a data-entry inconsistency on
            # ndlegis.gov's end, also noted in nd_legis_sync.py) -- keep only
            # the first occurrence so the enriched feed never has a
            # duplicate guid, which would break guid-based "already seen"
            # matching downstream.
            skipped_duplicate_count += 1
            continue
        seen_guids_this_run.add(item["guid"])
 
        ymd = url_date(item["link"])
        if ymd and datetime(*ymd).date() < today:
            # Meeting already passed -- no reason to scrape or include it;
            # the calendar-sync flow wouldn't add it anyway.
            skipped_past_count += 1
            continue
 
        if item["guid"] in cache:
            details = cache[item["guid"]]
            cached_count += 1
        else:
            print(f"Scraping (new): {item['title']}")
            details = fetch_meeting_details(item["link"])
            details["meeting_date"] = f"{ymd[0]:04d}-{ymd[1]:02d}-{ymd[2]:02d}" if ymd else None
            cache[item["guid"]] = details
            scraped_count += 1
            time.sleep(DELAY_BETWEEN_FETCHES_SECONDS)
 
        enriched_items.append(
            {
                **item,
                "enriched_description": build_description_field(item, details),
            }
        )
 
    write_feed_xml(enriched_items)
    validate_feed_xml()
 
    pruned_count = prune_cache(cache, today)
    save_cache(cache)
 
    print(
        f"Done. {len(enriched_items)} item(s) written to {OUTPUT_FEED_FILE} "
        f"({scraped_count} newly scraped, {cached_count} from cache, "
        f"{skipped_past_count} skipped as already past, "
        f"{skipped_duplicate_count} skipped as duplicate guid, "
        f"{pruned_count} stale cache entr{'y' if pruned_count == 1 else 'ies'} pruned)."
    )
 
 
if __name__ == "__main__":
    main()
